#!/bin/bash -x

BASE=$(basename -s .o5m $1)
BASEDIR=${PWD}

source ./osmdatalib

process_o5m city --keep="landuse=residential =industrial =commerical"
process_o5m railway --keep="railway=rail"
process_o5m roadbig --keep="highway=motorway =primary =trunk"
process_o5m roadmedium --keep="highway=secondary highway=tertiary"
process_o5m roadsmall --keep="highway=unclassified"
process_o5m water --keep="water=harbor =lake =natural =canal =river =reservoir =basin =riverbank natural=water waterway=river =canal =riverbank" 
