#!/bin/bash

BASE=$(basename -s o5m $1)
BASEDIR=${PWD}

function convert2shp() {

  cd ${BASEDIR}
  mkdir -p workdir/${BASE}/osm/$1_osm/
  mkdir -p workdir/${BASE}/shapefiles/$1_shapefiles/

osmconvert workdir/${BASE}/o5m/$1_o5m/${BASE}_$1.o5m --out-osm -o=workdir/${BASE}/osm/$1_osm/${BASE}_$1.osm 

ogr2ogr -skipfailures -f "ESRI Shapefile" workdir/${BASE}/shapefiles/$1_shapefiles workdir/${BASE}/osm/$1_osm/${BASE}_$1.osm

cd ${BASEDIR}/workdir/${BASE}/shapefiles/$1_shapefiles/
rename s/lines/$1_line/ line*
rename s/multipolygons/$1_area/ multipolygons*
  cd ${BASEDIR}
}

convert2shp railway
convert2shp roadbig
convert2shp roadmedium
convert2shp water
