#!/bin/bash -x

BASE=$(basename -s o5m $1)
BASEDIR=${PWD}

set -e


function reduceshp() {
  cd ${BASEDIR}/workdir/${BASE}/shapefiles/$1_shapefiles
  rm -rf $1
  grass -c EPSG:4326 $1 --exec sh $BASEDIR/reduce.sh $1
}

reduceshp roadbig
reduceshp roadmedium
reduceshp railway
reduceshp water
