#!/bin/bash -x

set -e

BASE=$(basename -s o5m $1)
BASEDIR=${PWD}

source ./osmdatalib

readshp_line roadbig
readshp_line roadmedium
readshp_line roadsmall
readshp_line railway
readshp_line water
readshp_area water
readshp_area city
