#!/bin/bash -x

BASE=$(basename -s o5m $1)
BASEDIR=${PWD}

set -e

source ./osmdatalib

reduceshp_line roadbig
reduceshp_line roadmedium
reduceshp_line railway
reduceshp_line water
reduceshp_area water
reduceshp_area city
