#!/bin/bash -x


function process_o5m() {
  NAME="$1"
  shift
  KEEP="$@"
  mkdir -p workdir/${BASE}/o5m/$NAME_o5m/
  time ./osmfilter workdir/${BASE}/o5m/${BASE}_small.o5m "${KEEP}" --out-o5m -o=${BASEDIR}/workdir/${BASE}/o5m//$NAME_o5m/${BASE}_$NAME.o5m
}

function readshp_point() {
  mkdir -p ${BASEDIR}/workdir/${BASE}/shapefiles/$1_shapefiles
  mkdir -p ${BASEDIR}/workdir/${BASE}/shapefiles/$1_shapefiles_redux
  cd ${BASEDIR}/workdir/${BASE}/shapefiles/$1_shapefiles
  if [ -d "${1}" ];
    then
      rm -rf "./$1"
  fi
  grass -c EPSG:4326 $1 --exec sh $BASEDIR/read_point.sh $1 ${BASEDIR}/workdir/${BASE}/shapefiles/$1_shapefiles
}


function readshp_area() {
  mkdir -p ${BASEDIR}/workdir/${BASE}/shapefiles/$1_shapefiles
  mkdir -p ${BASEDIR}/workdir/${BASE}/shapefiles/$1_shapefiles_redux
  cd ${BASEDIR}/workdir/${BASE}/shapefiles/$1_shapefiles
  if [ -d "${1}" ];
    then
      rm -rf "./$1"
  fi
  grass -c EPSG:4326 $1 --exec sh $BASEDIR/read_area.sh $1 ${BASEDIR}/workdir/${BASE}/shapefiles/$1_shapefiles
}

function readshp_line() {
  mkdir -p ${BASEDIR}/workdir/${BASE}/shapefiles/$1_shapefiles
  mkdir -p ${BASEDIR}/workdir/${BASE}/shapefiles/$1_shapefiles_redux
  cd ${BASEDIR}/workdir/${BASE}/shapefiles/$1_shapefiles
  if [ -d "${1}" ];
    then
      rm -rf "./$1"
  fi
  grass -c EPSG:4326 $1 --exec sh $BASEDIR/read_line.sh $1 ${BASEDIR}/workdir/${BASE}/shapefiles/$1_shapefiles
}

function reduceshp_area() {
  cd ${BASEDIR}/workdir/${BASE}/shapefiles/$1_shapefiles
  grass $1/PERMANENT --exec sh $BASEDIR/reduce_area.sh $1 ${BASEDIR}/workdir/${BASE}/shapefiles/$1_shapefiles 
}

function reduceshp_line() {
  cd ${BASEDIR}/workdir/${BASE}/shapefiles/$1_shapefiles
  grass $1/PERMANENT --exec sh $BASEDIR/reduce_line.sh $1 ${BASEDIR}/workdir/${BASE}/shapefiles/$1_shapefiles
}

function convert2shp() {
  cd ${BASEDIR}
  mkdir -p workdir/${BASE}/osm/$1_osm/
  mkdir -p workdir/${BASE}/shapefiles/$1_shapefiles/

osmconvert workdir/${BASE}/o5m/${BASE}_$1.o5m --out-osm -o=workdir/${BASE}/osm/$1_osm/${BASE}_$1.osm 

ogr2ogr -select "name" -skipfailures -f "ESRI Shapefile" workdir/${BASE}/shapefiles/$1_shapefiles workdir/${BASE}/osm/$1_osm/${BASE}_$1.osm

cd ${BASEDIR}/workdir/${BASE}/shapefiles/$1_shapefiles/
rename -f s/lines/$1_line/ line*
rename -f s/multipolygons/$1_area/ multipolygons*
  cd ${BASEDIR}
}


